### ISSUE TITLE
报错 No provider for NotificationsService!

### ISSUE THREAD

**Issue by Thinkingpey** [surmon-china/angular-admin#4]
报错堆栈：
No provider for NotificationsService!
    at NoProviderError.BaseError [as constructor] (http://localhost:6699/vendor.bundle.js:33938:34)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:6699/vendor.bundle.js:32012:16)

另外，哥们， 你拿别人的东西来做扩展做自己的东西没问题，至少要标注一下这套系统的来源吧。
https://akveo.github.io/ng2-admin/

**Comment by surmon-china** [comment]
标注了，并没有刻意去掉原作者来源，代码内的导航都依然保留官网的链接，跑起来之后可以看到的。

你的问题可能是package.json里缺少了对应依赖，
需要安装`npm install --save angular2-notifications`

相关文档在这里[angular2-notifications doc](https://github.com/flauc/angular2-notifications/blob/master/docs/toastNotifications.md)

**Comment by surmon-china** [comment]
请升级到最新版，问题源于`angular2-notifications`的升级.
